APP_STL := gnustl_static
APP_CPPFLAGS := -fexceptions -frtti -std=c++11 -DCOCOS2D_DEBUG=1 -DPROJ_AMAZON -DUSE_SDKBOX=0
TARGET_CPU_API := arm64-v8a
APP_ABI := arm64-v8a
APP_PLATFORM := android-19
NDK_DEBUG = 1

LOCAL_CFLAGS += -g
LOCAL_CPPFLAGS += -g
LOCAL_STRIP_MODULE :=false